version: '3'

services:
  nginx:
    build:
      context: .
      dockerfile: Dockerfile
    image: profile-website
    container_name: profile-codeopath
    ports:
      - "8081:80"  # Expose internal Nginx on port 8081
    restart: always
    volumes:
      - ./src/website:/usr/share/nginx/html:ro
    networks:
      - webnet

networks:
  webnet:
    driver: bridge
